include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    deprecated_member_use_from_same_package: warning
    sdk_version_async_exported_from_core: ignore
    unnecessary_null_comparison: warning
  exclude:
    - "lib/src/pb/*.dart"

linter:
  rules:
    avoid_print: false
    use_key_in_widget_constructors: false
