name: flutter_remote_piano
description: A toy piano app as an example of grpc-dart.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_midi: ^1.0.2
  grpc: ^2.8.0
  intl: ^0.16.1
  provider: ^4.3.2+3

dev_dependencies:
  intl_translation: ^0.17.10+1

flutter:
  uses-material-design: true

  assets:
    - assets/sf2/
