name: flutter_remote_piano
description: A toy piano app as an example of grpc-dart.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_midi: ^1.1.0
  grpc: ^3.0.0
  intl: ^0.17.0
  provider: ^5.0.0

dependency_overrides:
  crypto: ^3.0.1
  intl: ^0.17.0

dev_dependencies:
  intl_translation: ^0.17.10+1

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/sf2/
